#!/usr/bin/env python3
"""
music_gen.py - dark ambient background music bed for the shorts.

Strategy (the pipeline can never break on music)
------------------------------------------------
1. try_gemini_music(): asks the Gemini API for a dark, cinematic, ambient
   track. The public Gemini API has no music-generation endpoint today
   (Lyria is Vertex-AI-only), so this hook normally reports "not available"
   and moves on. It activates automatically the day Google ships a music
   model - or right now if you set GEMINI_MUSIC_MODEL=<name> and one works.
2. Fallback (default path): a procedural dark-ambient synthesizer renders a
   ~30-second loopable bed locally with numpy -> WAV: a detuned D-minor
   drone, a slow fifth, a faint minor-third shimmer and low-passed cave-like
   air, all breathing on slow LFOs. Every tone completes an integer number
   of cycles across the loop, so step2's afx.AudioLoop splice is click-free.
3. step2_render_video.py loops the bed to the exact voiceover duration and
   mixes it at 10% volume (volumex-style) under the edge-tts narration.

Env knobs
---------
    BG_MUSIC=off          disable the music bed entirely (or --music none)
    MUSIC_LEVEL=0.1       mixing volume of the bed (default 0.1)
    GEMINI_MUSIC_MODEL    optional: model name to attempt Gemini audio with
"""

from __future__ import annotations

import math
import os
import wave
from pathlib import Path

import numpy as np

SAMPLE_RATE = 44100
LOOP_SECONDS = 30.0
MUSIC_FILENAME = "_music_bed.wav"

# D-minor drone frequencies (Hz): root, fifth, octave, minor third
DRONE_HZ = (73.42, 110.00, 146.83, 174.61)
DRONE_GAIN = (0.50, 0.30, 0.16, 0.10)


def try_gemini_music(duration: float, out_path: Path) -> Path | None:
    """Attempt Gemini-generated music. Returns a path on success, else None.

    Sends a text prompt and looks for inline audio data in the response -
    exactly what a future Gemini music model would return. Set
    GEMINI_MUSIC_MODEL to force an attempt against a specific model."""
    model = (os.getenv("GEMINI_MUSIC_MODEL", "") or "").strip()
    api_key = (os.getenv("GEMINI_API_KEY", "") or "").strip()
    if not model or not api_key:
        return None
    try:
        import base64

        import requests
        prompt = (f"Generate a dark, cinematic, ambient background music track "
                  f"of about {min(duration, 30):.0f} seconds: low drones, slow "
                  "swells, subtle tension, no melody, no percussion.")
        r = requests.post(
            "https://generativelanguage.googleapis.com/v1beta/models/"
            f"{model}:generateContent",
            headers={"x-goog-api-key": api_key},
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=60)
        data = r.json()
        parts = (data.get("candidates") or [{}])[0].get(
            "content", {}).get("parts", [])
        for part in parts:
            inline = part.get("inlineData") or part.get("inline_data")
            if inline and inline.get("data"):
                out_path.write_bytes(base64.b64decode(inline["data"]))
                print(f"      music: generated by Gemini ({model}) "
                      f"-> {out_path.name}")
                return out_path
        print(f"      music: Gemini model '{model}' returned no audio "
              "- using the built-in ambient synth")
    except Exception as exc:
        print(f"      music: Gemini attempt failed ({str(exc)[:80]}) "
              "- using the built-in ambient synth")
    return None


def _loop_safe(freq: float, loop_seconds: float) -> float:
    """Snap a frequency so it completes an integer number of cycles per loop
    (guarantees a click-free audio_loop splice)."""
    cycles = max(1, round(freq * loop_seconds))
    return cycles / loop_seconds


def _lowpass_fft(x: np.ndarray, cutoff: float, sr: int) -> np.ndarray:
    """Circular (FFT) low-pass - periodic by construction, so the loop
    boundary stays smooth."""
    spec = np.fft.rfft(x)
    freqs = np.fft.rfftfreq(len(x), 1.0 / sr)
    spec /= (1.0 + (freqs / max(cutoff, 1.0)) ** 2)
    return np.fft.irfft(spec, n=len(x))


def synthesize_dark_ambient(duration: float, out_path: Path,
                            seed: int | None = None,
                            mood: str = "serious") -> Path:
    """Render a loop-safe dark ambient bed (stereo 16-bit WAV).

    `mood` (from the script's dominant emotion) subtly re-voicing the bed:
    faster pulse for intense, softer air for calm, a bright shimmer for
    curious, a major third for playful, a rising fifth for triumphant. The
    default 'serious' bed is unchanged from the classic pipeline."""
    rng = np.random.default_rng(seed)
    n = int(SAMPLE_RATE * duration)
    t = np.arange(n) / SAMPLE_RATE
    tt = t / max(duration, 1e-6)              # 0..1 across the loop

    lfo_mul = {"intense": 2.1, "urgent": 1.8, "calm": 0.6}.get(mood, 1.0)
    air_cut = {"calm": 160.0, "intense": 320.0}.get(mood, 220.0)
    peak = {"calm": 0.40, "intense": 0.50}.get(mood, 0.45)

    # 1) detuned drone stack (slow beating pairs, loop-safe frequencies)
    mono = np.zeros(n)
    for base, gain in zip(DRONE_HZ, DRONE_GAIN):
        f1 = _loop_safe(base, duration)
        f2 = _loop_safe(base * 1.006, duration)   # ~0.6% detune -> slow beat
        lfo = 0.75 + 0.25 * np.sin(2 * np.pi * tt * max(1, round(0.061 * lfo_mul * duration)))
        mono += gain * lfo * (0.62 * np.sin(2 * np.pi * f1 * t)
                              + 0.38 * np.sin(2 * np.pi * f2 * t))

    # 1b) mood colors
    if mood == "intense":
        pulse = 0.85 + 0.15 * np.sign(np.sin(2 * np.pi * _loop_safe(0.5, duration) * t))
        mono *= pulse
    elif mood == "playful":
        mono += 0.10 * np.sin(2 * np.pi * _loop_safe(185.0, duration) * t)  # F#3 major third
    elif mood == "triumphant":
        swell = 0.5 + 0.5 * np.sin(2 * np.pi * tt * 1 - np.pi / 2)          # 1 cycle/loop
        mono += 0.12 * swell * np.sin(2 * np.pi * _loop_safe(220.0, duration) * t)

    # 2) faint high shimmer, slow tremolo
    shimmer_hz = {"curious": 660.0, "urgent": 523.25}.get(mood, 440.0)
    shimmer_f = _loop_safe(shimmer_hz, duration)
    trem_rate = max(1, round(0.09 * duration)) if mood != "urgent" \
        else max(1, round(0.35 * duration))
    trem = 0.5 + 0.5 * np.sin(2 * np.pi * tt * trem_rate + 1.3)
    shimmer_gain = {"calm": 0.03, "curious": 0.07}.get(mood, 0.05)
    mono += shimmer_gain * trem * np.sin(2 * np.pi * shimmer_f * t)

    # 3) low-passed noise 'air', slow swell (circular filter = loop-safe)
    noise = rng.standard_normal(n) * 0.5
    swell = 0.55 + 0.45 * np.sin(2 * np.pi * tt * max(1, round(0.043 * duration)) + 0.7)
    mono += 0.22 * swell * _lowpass_fft(noise, air_cut, SAMPLE_RATE)

    # 4) global slow breathing + click-free edges
    breath = 0.82 + 0.18 * np.sin(2 * np.pi * tt * max(1, round(0.05 * duration)) + 2.1)
    mono *= breath
    fade = min(2.0, duration * 0.08)
    nf = max(1, int(fade * SAMPLE_RATE))
    edge = np.ones(n)
    edge[:nf] = np.linspace(0, 1, nf)
    edge[-nf:] = np.linspace(1, 0, nf)
    mono *= edge

    # normalize + stereo width (right channel delayed a few ms)
    mono /= max(np.abs(mono).max(), 1e-9)
    right = np.roll(mono, int(0.011 * SAMPLE_RATE))
    st = np.stack([mono * peak, right * peak], axis=1)
    frames = (st * 32767).astype(np.int16)

    with wave.open(str(out_path), "wb") as wav:
        wav.setnchannels(2)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        wav.writeframes(frames.tobytes())
    return out_path


def ensure_music_bed(run_folder: Path, duration: float,
                     mood: str = "serious") -> Path | None:
    """Return a music bed file covering `duration` (cached per run folder).

    Honors BG_MUSIC=off. Tries Gemini first (see try_gemini_music), then
    falls back to the built-in procedural synth. Never raises."""
    if (os.getenv("BG_MUSIC", "") or "").strip().lower() in ("off", "none", "0", "false"):
        return None
    mood = (mood or "serious").strip().lower()
    if mood not in ("intense", "serious", "curious", "playful", "urgent",
                    "calm", "triumphant"):
        mood = "serious"
    out_path = run_folder / (MUSIC_FILENAME if mood == "serious"
                             else f"_music_bed_{mood}.wav")
    if out_path.is_file() and out_path.stat().st_size > 100_000:
        print(f"      music: reusing cached bed {out_path.name}")
        return out_path
    got = try_gemini_music(duration, out_path)
    if got is not None:
        return got
    loop_len = float(min(LOOP_SECONDS, max(6.0, duration)))
    synthesize_dark_ambient(loop_len, out_path, mood=mood)
    print(f"      music: synthesized {loop_len:.0f}s {mood} bed "
          f"({out_path.name}, loops to {duration:.1f}s)")
    return out_path
