#!/usr/bin/env python3
"""
step_thumbnail.py - automatic, $0-cost thumbnail generation for every short.

Runs AFTER step2 (needs word_timings.json) and BEFORE the upload step, so the
selected thumbnail can be attached automatically:
    YouTube Shorts : 1080x1920 JPG -> thumbnails.set right after videos().insert
                     (Shorts surfaces are 9:16 - a 16:9 image gets
                     center-cropped there and loses ~68% of its width)
    Instagram      : 1080x1920 PNG -> clip_upload(thumbnail=...) cover frame
    Legacy extra   : 1280x720 JPG  -> kept for 16:9 embed/compat surfaces

Design (the FREE pipeline - no Gemini image quota, no video-frame grabs)
-----------------------------------------------------------------------
Every variant is a CREATIVE ILLUSTRATION generated by the public
Pollinations.ai Flux endpoint (no API key, no account, literally $0),
with the headline typeset LOCALLY in the bundled Anton font so spelling is
deterministic and the text stays readable at mobile-feed sizes:

    variant "hook"      = illustration for the hook beat + the hook text
    variant "midpoint"  = illustration for the strongest mid-video beat
    variant "clean"     = atmospheric illustration, no text at all

Each variant is rendered at TWO native aspect ratios (never a stretch):
    youtube     : 1080x1920 JPG (9:16 SHORTS-FIRST upload spec, <2MB loop)
    instagram   : 1080x1920 PNG (9:16 Reels cover - same vertical art + text)
    youtube_wide: 1280x720 JPG  (16:9 legacy extra, <2MB re-encode loop)
The vertical render is made ONCE and split into the YouTube JPG and the
Instagram PNG - one AI image, two encodes, zero wasted generation time.

Provider chain (THUMB_IMAGE_PROVIDER):
    auto (default) : pollinations -> local_artwork poster fallback
                     (the step is NEVER empty-handed)
    pollinations   : Pollinations only (failures skip the variant)
    local          : offline poster art only (no network)
    gemini         : LEGACY paid path (Gemini image models) - needs a key
                     and image-model quota; kept for completeness.

The Pollinations quirk: it respects aspect ratio but not exact pixels
(flux returns 1024x576 / 576x1024), so images are cover-cropped + LANCZOS
resized to the exact spec. Requests are deterministic (seed = hash of
run:variant:tag) and retried with jitter; a global time budget makes sure
the whole step can never stall the pipeline. Any failure prints a WARNING
and exits 0 (unless --strict) - a thumbnail problem can never block
publishing.

Outputs (review folder: output/<run_id>/thumbnails/)
    hook_youtube.jpg  hook_instagram.png  (+ same for midpoint/clean)
    preview_mobile_<selected>.png        (tiny legibility proof)
    thumbnail_manifest.json              (everything the upload step needs)

Config (env or CLI, all optional)
    THUMBNAIL_VARIANT        hook | midpoint | clean   (default hook)
    AUTO_UPLOAD_THUMBNAIL    true | false              (default true)
    THUMB_IMAGE_PROVIDER     auto | pollinations | local | gemini
    THUMB_IMAGE_MODEL        force one Pollinations model (default flux,turbo)
    THUMB_POLLINATIONS_BUDGET  global seconds for all network art
                             (default 420 - after that, auto falls back to
                             local posters instantly)
    GEMINI_THUMB_MODEL       text-shortening model (default flash-lite;
                             TEXT quota is free - only used to shorten hooks)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

# Reuse the renderer's font resolution + measured word wrap so the thumbnail
# text matches the caption style exactly (same face, same wrap behaviour).
try:
    from step2_render_video import resolve_font, wrap_by_width
except Exception:                                        # pragma: no cover
    def resolve_font(explicit=None):
        cand = [ROOT / "fonts" / "Anton-Regular.ttf"]
        for c in cand:
            if c.is_file():
                return str(c)
        return "DejaVuSans-Bold"

    def wrap_by_width(text, font, size, stroke, max_width):
        from PIL import ImageFont
        probe = ImageFont.truetype(font, size)
        lines, cur = [], ""
        for word in text.upper().split():
            cand = f"{cur} {word}".strip()
            if not cur or probe.getlength(cand) + 2 * stroke <= max_width:
                cur = cand
            else:
                lines.append(cur)
                cur = word
        if cur:
            lines.append(cur)
        return lines

try:    # local .env (CI injects real env vars itself)
    from step1_generate import load_environment
except Exception:                                        # pragma: no cover
    def load_environment(_):
        return None

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

IG_SIZE = (1080, 1920)         # 9:16 vertical = the Shorts-first upload spec
YT_SHORTS_SIZE = IG_SIZE       # YouTube Shorts thumbnail uses the vertical
YT_SIZE = (1280, 720)          # legacy 16:9 thumbnail (secondary output)

# Shorts-UI safe band on a vertical canvas - keep all text inside it:
#   top    ~ 8%  (feed icons / camera UI)
#   bottom ~28%  (title + username + audio overlay in the Shorts feed)
# TEXT_CENTER_Y_VERTICAL = 0.36 centers the headline block in that band.

DEFAULT_VARIANT = "hook"       # hook | midpoint | clean
ACCENT_YELLOW = (245, 217, 10)     # #F5D90A - the channel's hook yellow
ACCENT_WHITE = (255, 255, 255)
STROKE_COLOR = (0, 0, 0)
MAX_WIDTH_PCT = 0.84           # same width cap as the captions (v3)
MAX_LINES = 3                  # thumbnail text must stay compact

FONT_SIZE_PCT_START = 0.105    # headline starts at ~10.5% of canvas width
FONT_SIZE_PCT_MIN = 0.045      # ...and shrinks only as far as 4.5% to fit

TEXT_CENTER_Y_VERTICAL = 0.36      # upper-middle: inside the Shorts-safe band
TEXT_CENTER_Y_WIDE = 0.44

SCRIM_MAX_ALPHA = 95               # soft scrim directly behind the text block

TRUNCATE_WORDS = 6                 # hook longer than this -> shorten it

# --- Pollinations (free image generation, no key needed) --------------------
POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}"
POLLINATIONS_MODELS = ["flux", "turbo"]       # quality first, speed second
POLLINATIONS_TIMEOUT = 90                     # seconds per HTTP request
POLLINATIONS_MODEL_BUDGET = 150               # seconds per model (each model
                                              # always gets its FIRST try)
POLLINATIONS_MAX_ATTEMPTS = 6                 # total attempts, all models
POLLINATIONS_GLOBAL_BUDGET = float(           # network art budget for the
    os.getenv("THUMB_POLLINATIONS_BUDGET", "420"))   # whole step, seconds
POLLINATIONS_MIN_SIDE = 500                   # reject tiny/broken responses

PROVIDER = (os.getenv("THUMB_IMAGE_PROVIDER", "") or "auto").strip().lower()
if PROVIDER not in ("auto", "pollinations", "local", "gemini"):
    print(f"WARNING: unknown THUMB_IMAGE_PROVIDER '{PROVIDER}' - using auto")
    PROVIDER = "auto"
POLLINATIONS_MODEL_ENV = (os.getenv("THUMB_IMAGE_MODEL", "") or "").strip()

# --- text shortening (Gemini TEXT quota is free; local fallback exists) -----
try:
    from step1_generate import resolve_models as _resolve_models
except Exception:                                        # pragma: no cover
    def _resolve_models():
        return ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"]
_GEMINI_FIRST = os.getenv("GEMINI_THUMB_MODEL", "gemini-2.5-flash-lite")
GEMINI_MODELS = list(dict.fromkeys(
    [_GEMINI_FIRST] + list(_resolve_models())))

STOPWORD_TAIL = {"a", "an", "and", "are", "but", "for", "in", "is", "of",
                 "on", "or", "that", "the", "this", "to", "with", "you",
                 "your", "it", "its", "was", "were", "so", "as", "at", "by"}

# emotion (or any text) -> rim-glow hue for the offline poster fallback
GLOW_HUES = {
    "anger": 0, "rage": 0, "fury": 0, "hatred": 0,
    "fear": 220, "anxiety": 220, "dread": 220, "panic": 220,
    "envy": 120, "jealous": 120, "greed": 120,
    "pride": 285, "ego": 285, "narciss": 285,
    "curiosity": 45, "secret": 45, "mystery": 45, "hidden": 45,
    "calm": 190, "silence": 190, "control": 190, "power": 190,
    "manipul": 262, "decept": 262, "betray": 262, "dark": 262,
}
GLOW_DEFAULT_HUE = 262                    # the channel's violet


def env_flag(name: str, default: str = "on") -> bool:
    return (os.getenv(name, default) or default).strip().lower() not in \
        ("0", "off", "none", "false")


# ---------------------------------------------------------------------------
# Deterministic seeding + Pollinations client (free, no API key)
# ---------------------------------------------------------------------------

def seed_for(run_name: str, variant: str, tag: str) -> int:
    """Same run + variant + size -> same image, every time (reproducible)."""
    digest = hashlib.sha256(f"{run_name}:{variant}:{tag}".encode()).hexdigest()
    return int(digest[:8], 16)


def _accept_pollinations(content: bytes, content_type: str) -> tuple[bool, str]:
    """Acceptance gate: 200 + image/* + >20KB + PIL-verify + min side >= 500."""
    if not (content and content[:1]):
        return False, "empty body"
    if len(content) <= 20 * 1024:
        return False, f"too small ({len(content)}B)"
    if "image" not in content_type.lower():
        return False, f"content-type {content_type[:40]!r}"
    from io import BytesIO
    from PIL import Image
    try:
        probe = Image.open(BytesIO(content))
        probe.verify()
        img = Image.open(BytesIO(content))
        if min(img.size) < POLLINATIONS_MIN_SIDE:
            return False, f"resolution too low {img.size}"
    except Exception as exc:
        return False, f"corrupt image ({str(exc)[:50]})"
    return True, ""


def pollinations_image(prompt: str, wide: bool, seed: int):
    """Fetch one illustration. Returns (bytes, content_type, model) or
    (None, '', ''). Per-model time budget + jittered retries; every model in
    the chain always gets at least one attempt."""
    import requests as rq

    models = [POLLINATIONS_MODEL_ENV] if POLLINATIONS_MODEL_ENV \
        else list(POLLINATIONS_MODELS)
    req_w, req_h = (1280, 720) if wide else (1080, 1920)
    attempt = 0

    for model in models:
        model_deadline = time.time() + POLLINATIONS_MODEL_BUDGET
        while attempt < POLLINATIONS_MAX_ATTEMPTS:
            attempt += 1
            use_seed = (seed + attempt * 17) % 9_999_991   # jitter: new seed
            params = {"width": req_w, "height": req_h, "model": model,
                      "seed": use_seed, "nologo": "true", "private": "true"}
            url = POLLINATIONS_URL.format(prompt=quote(prompt, safe=""))
            try:
                resp = rq.get(url, params=params,
                              timeout=POLLINATIONS_TIMEOUT)
            except Exception as exc:
                print(f"      pollinations {model}: request error "
                      f"({str(exc)[:60]})")
                if attempt > 1 and time.time() > model_deadline:
                    break
                time.sleep(min(8, 2 + 2 * attempt))
                continue

            ok, why = _accept_pollinations(resp.content,
                                           resp.headers.get("content-type",
                                                            ""))
            if ok and resp.status_code == 200:
                print(f"      pollinations: got {len(resp.content)//1024}KB "
                      f"via {model} (seed {use_seed})")
                return resp.content, resp.headers.get("content-type", ""), model
            print(f"      pollinations {model}: try {attempt} rejected "
                  f"(HTTP {resp.status_code}, {why})")

            # 'attempt > 1' guarantees each model its FIRST try even if flux
            # burned the whole budget - turbo still gets a shot.
            if attempt > 1 and time.time() > model_deadline:
                print(f"      pollinations {model}: budget exhausted, "
                      f"handing over to the next model")
                break
            time.sleep(min(8, 2 + 2 * attempt))

    return None, "", ""


def save_image(data: bytes, dest: Path, wide: bool) -> Path:
    """Cover-crop + LANCZOS-resize to the EXACT spec (flux ignores pixels),
    then save JPG (<=2MB loop) or PNG."""
    from io import BytesIO
    from PIL import Image, ImageOps

    img = Image.open(BytesIO(data)).convert("RGB")
    target = YT_SIZE if wide else IG_SIZE
    out = ImageOps.fit(img, target, Image.LANCZOS, centering=(0.5, 0.45))

    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.suffix.lower() == ".jpg":
        quality = 92
        while quality >= 70:
            out.save(dest, "JPEG", quality=quality, optimize=True)
            if dest.stat().st_size <= 2 * 1024 * 1024:   # API limit 2 MB
                break
            quality -= 6
    else:
        out.save(dest, "PNG")
    return dest


# ---------------------------------------------------------------------------
# Prompt builder (strictly text-free illustrations for the free path)
# ---------------------------------------------------------------------------

def build_prompt(variant: str, caption: str, ctx: dict, wide: bool,
                 paint_text: bool = True) -> str:
    concept = str(ctx.get("visual_concept") or caption or
                  "a lone figure facing their own shadow").strip()
    emotion = str(ctx.get("emotion") or "tension").strip()

    if wide:
        aspect = ("wide 16:9 cinematic composition, main subject in the "
                  "center, generous space above")
    else:
        aspect = ("vertical 9:16 composition, main subject centered in the "
                  "middle band of the frame, calm dark negative space above "
                  "and below the subject")

    if paint_text:
        text_note = (f'Include the exact bold headline text "{caption}" at '
                     "the top, spelled EXACTLY letter for letter.")
    else:
        text_note = ("Absolutely NO text, letters, numbers, words, captions, "
                     "logos, watermarks or typography of any kind in the "
                     "image. Keep the upper-middle area as clean dark "
                     "negative space (a headline is added there later).")

    style = ("moody cinematic digital illustration, dark psychology editorial "
             "art, dramatic rim lighting, deep navy and violet palette with "
             "one small warm yellow accent light, heavy shadows, subtle film "
             "grain, high contrast, symbolic, thought-provoking, no gore")

    return (f"{concept}. Mood: {emotion}. {aspect}. Style: {style}. "
            f"{text_note}")


# ---------------------------------------------------------------------------
# Offline poster fallback (local_artwork): gradient + rim glow + grain
# ---------------------------------------------------------------------------

def _emotion_hue(ctx: dict) -> int:
    haystack = " ".join(str(ctx.get(k, "") or "")
                        for k in ("emotion", "visual_concept", "caption"))
    low = haystack.lower()
    for key, hue in GLOW_HUES.items():
        if key in low:
            return hue
    return GLOW_DEFAULT_HUE


def local_artwork(ctx: dict, wide: bool, seed: int) -> Path:
    """Never-fail offline poster: navy->violet gradient, emotion-tinted rim
    glow, film grain, vignette. NO text (the headline is overlaid after)."""
    import colorsys
    import numpy as np
    from PIL import Image, ImageDraw, ImageFilter

    w, h = YT_SIZE if wide else IG_SIZE
    rng = np.random.default_rng(seed)

    # 1. vertical navy -> violet gradient (slightly tilted per seed)
    top = np.array([11, 16, 38], dtype=np.float32)
    bot = np.array([42, 27, 74], dtype=np.float32)
    t = np.linspace(0.0, 1.0, h, dtype=np.float32)[:, None, None]
    img = top * (1 - t) + bot * t                       # (h,1,3)
    img = np.broadcast_to(img, (h, w, 3)).copy()
    tilt = int(rng.integers(0, w // 6))
    if tilt:
        shift = np.linspace(0.06, -0.06, w, dtype=np.float32)
        img += shift[None, :, None] * 60.0

    # 2. rim glow: radial ellipse of the emotion hue behind the subject area
    hue = _emotion_hue(ctx) / 360.0
    glow_rgb = np.array([int(c * 255) for c in colorsys.hsv_to_rgb(hue, 0.75,
                                                                   0.95)],
                        dtype=np.float32)
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    cy, cx = h * (0.30 if not wide else 0.34), w * 0.5
    ry, rx = h * 0.34, w * 0.55
    d2 = ((yy - cy) / ry) ** 2 + ((xx - cx) / rx) ** 2
    glow = np.clip(1.0 - d2, 0.0, 1.0) ** 2.2
    img += glow[:, :, None] * glow_rgb * (0.55 + 0.1 * rng.random())

    # 3. film grain + vignette
    img += rng.normal(0.0, 9.0, img.shape).astype(np.float32)
    vign = 1.0 - 0.45 * np.clip((d2 - 0.55) / 1.2, 0.0, 1.0)
    img *= vign[:, :, None]

    frame = Image.fromarray(np.clip(img, 0, 255).astype(np.uint8))
    frame = frame.filter(ImageFilter.GaussianBlur(0.6))
    return frame


# ---------------------------------------------------------------------------
# Typography: Anton headline overlaid locally (spelling is deterministic)
# ---------------------------------------------------------------------------

def _fit_font_size(text: str, font_path: str, canvas_w: int) -> int:
    """Largest size (from FONT_SIZE_PCT_START down to FONT_SIZE_PCT_MIN of
    canvas width) that still wraps to <= MAX_LINES inside the width cap."""
    lo = int(canvas_w * FONT_SIZE_PCT_MIN)
    hi = int(canvas_w * FONT_SIZE_PCT_START)
    best = lo
    for size in range(hi, lo - 1, -2):
        stroke = max(4, size // 12)
        max_w = int(canvas_w * MAX_WIDTH_PCT)
        if len(wrap_by_width(text, font_path, size, stroke, max_w)) <= MAX_LINES:
            best = size
            break
    return max(best, lo)


def _draw_text_block(canvas, text: str, font_path: str, wide: bool) -> dict:
    """Bold title-card style headline, centered upper-middle. Returns layout
    dict with the composited RGBA layer."""
    from PIL import Image, ImageDraw, ImageFilter

    w, h = canvas.size
    size = _fit_font_size(text, font_path, w)
    if size < w * FONT_SIZE_PCT_START * 0.92:
        print(f"      text: font auto-shrunk to {size}px to stay <= "
              f"{MAX_LINES} lines")
    stroke = max(4, size // 12)
    max_w = int(w * MAX_WIDTH_PCT)
    lines = wrap_by_width(text, font_path, size, stroke, max_w)
    probe_h = int(size * 1.24)
    block_w = max_w
    block_h = probe_h * len(lines) + stroke * 2

    cx = w // 2
    cy = int(h * (TEXT_CENTER_Y_WIDE if wide else TEXT_CENTER_Y_VERTICAL))
    x0 = max(0, cx - block_w // 2)
    y0 = max(0, cy - block_h // 2)

    # soft scrim behind the text block so it reads on any artwork
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    pad = int(size * 0.55)
    scrim = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ImageDraw.Draw(scrim).rectangle(
        [max(0, x0 - pad), max(0, y0 - pad // 2),
         min(w, x0 + block_w + pad), min(h, y0 + block_h + pad // 2)],
        fill=(0, 0, 0, SCRIM_MAX_ALPHA))
    scrim = scrim.filter(ImageFilter.GaussianBlur(size * 0.45))
    layer = Image.alpha_composite(layer, scrim)

    draw = ImageDraw.Draw(layer)
    from PIL import ImageFont
    font = ImageFont.truetype(font_path, size)
    for i, line in enumerate(lines):
        bbox = draw.textbbox((0, 0), line, font=font, stroke_width=stroke)
        lw = bbox[2] - bbox[0]
        lx = x0 + (block_w - lw) // 2 - bbox[0]
        ly = y0 + i * probe_h - bbox[1]
        # drop shadow -> stroke -> fill (same look as the v2 title card)
        draw.text((lx + max(2, size // 40), ly + max(3, size // 26)), line,
                  font=font, fill=(0, 0, 0, 150), stroke_width=stroke,
                  stroke_fill=STROKE_COLOR + (150,))
        draw.text((lx, ly), line, font=font, fill=ACCENT_YELLOW,
                  stroke_width=stroke, stroke_fill=STROKE_COLOR + (255,))

    return {"layer": layer, "lines": lines, "font_px": size,
            "block": [x0, y0, x0 + block_w, y0 + block_h]}


def _png_to_jpg_bounded(src: Path, dest: Path) -> None:
    """Re-encode a finished PNG render as JPG under the 2 MB thumbnails.set
    cap (same quality walk-down loop as save_image)."""
    from PIL import Image

    img = Image.open(src).convert("RGB")
    quality = 92
    dest.parent.mkdir(parents=True, exist_ok=True)
    while quality >= 70:
        img.save(dest, "JPEG", quality=quality, optimize=True)
        if dest.stat().st_size <= 2 * 1024 * 1024:
            break
        quality -= 6


def overlay_headline(path: Path, caption: str, wide: bool) -> dict:
    """Typeset the headline ONTO the image at `path`, in place (JPG q92 /
    PNG). Returns the layout dict for the manifest."""
    from PIL import Image

    img = Image.open(path).convert("RGBA")
    layout = _draw_text_block(img, caption, resolve_font(None), wide)
    img = Image.alpha_composite(img, layout.pop("layer"))
    if path.suffix.lower() == ".jpg":
        quality = 92
        rgb = img.convert("RGB")
        while quality >= 70:
            rgb.save(path, "JPEG", quality=quality, optimize=True)
            if path.stat().st_size <= 2 * 1024 * 1024:
                break
            quality -= 6
    else:
        img.convert("RGB").save(path, "PNG")
    return layout


# ---------------------------------------------------------------------------
# Text: shortening (Gemini text quota is free, local fallback guaranteed)
# ---------------------------------------------------------------------------

def _local_shorten(text: str, emphasis: list[str] | None = None) -> str:
    """No-Gemini fallback: emphasis phrase if it is punchy, else head words."""
    words = re.sub(r"[^A-Za-z0-9' ]+", " ", text).split()
    if not words:
        return text.upper()[:40]
    if emphasis:
        phrase = re.sub(r"[^A-Za-z0-9' ]+", " ", " ".join(emphasis)).split()
        if 3 <= len(phrase) <= TRUNCATE_WORDS:
            return " ".join(phrase).upper()
    keep = words[:TRUNCATE_WORDS]
    while len(keep) > 3 and keep[-1].lower() in STOPWORD_TAIL:
        keep.pop()
    return " ".join(keep).upper()


def gemini_shorten(texts: dict[str, str], api_key: str | None) -> dict[str, str]:
    """One quick TEXT call: '3-6 word punchy thumbnail caption, all caps'.
    Raises on total failure so callers can fall back to the local heuristic."""
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY not set")
    from google import genai
    from google.genai import types

    parts = "\n".join(f"{k.upper()}_TEXT: {v}" for k, v in texts.items())
    prompt = (
        "Shorten each line below into a punchy thumbnail caption.\n"
        "RULES: 3 to 6 words, ALL CAPS, no period, keep the strongest "
        "tension/curiosity words, do not invent new claims.\n\n"
        f"{parts}\n\n"
        'Return STRICT JSON only: {"hook": "...", "mid": "..."} '
        "(include only the keys given)."
    )
    client = genai.Client(
        api_key=api_key, http_options=types.HttpOptions(timeout=45000))
    last_exc: Exception | None = None
    for model in GEMINI_MODELS:
        for attempt in (1, 2):
            try:
                resp = client.models.generate_content(
                    model=model, contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.4, max_output_tokens=120,
                        response_mime_type="application/json"))
                raw = re.sub(r"^```(?:json)?|```$", "",
                             (resp.text or "").strip(), flags=re.MULTILINE)
                data = json.loads(raw)
                out = {}
                for key, original in texts.items():
                    value = str(data.get(key, "")).strip().strip('"').upper()
                    value = re.sub(r"[.\u2026]+$", "", value).strip()
                    n_words = len(value.split())
                    if not (3 <= n_words <= 8):
                        raise ValueError(f"{key}: bad shorten ({value[:40]!r})")
                    out[key] = value
                print(f"      gemini shorten ok ({model})")
                return out
            except Exception as exc:
                last_exc = exc
                if attempt == 1:
                    time.sleep(1.5)
        print(f"      gemini shorten: {model} failed ({str(last_exc)[:70]})")
    raise RuntimeError(f"gemini shorten failed ({str(last_exc)[:80]})")


def resolve_thumbnail_texts(hook_text: str, mid_text: str,
                            emphasis: list[str], api_key: str | None) -> dict:
    """Shorten only what exceeds the word budget; one Gemini call for all."""
    need = {"hook": len(hook_text.split()) > TRUNCATE_WORDS}
    mid_short = ""
    if mid_text:
        need["mid"] = len(mid_text.split()) > TRUNCATE_WORDS
    result = {"hook": hook_text.upper(), "mid": mid_text.upper(),
              "hook_source": "full", "mid_source": "full"}
    if not any(need.values()):
        return result
    try:
        ask = {k: (hook_text if k == "hook" else mid_text)
               for k, wanted in need.items() if wanted}
        got = gemini_shorten(ask, api_key)
    except Exception as exc:
        print(f"      shorten: Gemini unavailable -> local heuristic "
              f"({str(exc)[:70]})")
        if need.get("hook"):
            result["hook"] = _local_shorten(hook_text, emphasis)
            result["hook_source"] = "local_shorten"
        if need.get("mid"):
            result["mid"] = _local_shorten(mid_text)
            result["mid_source"] = "local_shorten"
        return result
    if need.get("hook"):
        result["hook"] = got["hook"]
        result["hook_source"] = "gemini"
    if need.get("mid"):
        result["mid"] = got["mid"]
        result["mid_source"] = "gemini"
    return result

# ---------------------------------------------------------------------------
# Legacy PAID path (only when THUMB_IMAGE_PROVIDER=gemini): image models with
# text baked in + a vision check. Kept for completeness; the CI free tier has
# image quota 0, so the default 'auto' chain never touches this.
# ---------------------------------------------------------------------------

_GEMINI_IMAGE_MODELS = ["gemini-2.5-flash-image",
                        "gemini-2.0-flash-preview-image-generation"]


def gemini_image(prompt: str, api_key: str) -> bytes | None:
    from google import genai
    from google.genai import types
    client = genai.Client(api_key=api_key,
                          http_options=types.HttpOptions(timeout=120000))
    for model in _GEMINI_IMAGE_MODELS:
        try:
            resp = client.models.generate_content(
                model=model, contents=prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"], temperature=0.7))
            for cand in (resp.candidates or []):
                for part in (cand.content.parts or []):
                    if getattr(part, "inline_data", None) and \
                            part.inline_data.data:
                        print(f"      gemini image ok ({model})")
                        return part.inline_data.data
            raise RuntimeError("no image part in response")
        except Exception as exc:
            print(f"      gemini image: {model} failed ({str(exc)[:70]})")
    return None


def gemini_text_check(image_bytes: bytes, expected: str, api_key: str) -> bool:
    """Vision pass: does the baked-in text match the expected caption?"""
    try:
        from google import genai
        from google.genai import types
        from io import BytesIO
        from PIL import Image
        buf = BytesIO()
        Image.open(BytesIO(image_bytes)).convert("RGB").save(buf, "PNG")
        client = genai.Client(api_key=api_key,
                              http_options=types.HttpOptions(timeout=60000))
        resp = client.models.generate_content(
            model=GEMINI_MODELS[0],
            contents=[types.Part.from_bytes(data=buf.getvalue(),
                                            mime_type="image/png"),
                      "Transcribe EXACTLY the text visible in this image. "
                      "Reply with the text only."],
            config=types.GenerateContentConfig(max_output_tokens=60,
                                               temperature=0))
        got = re.sub(r"[^A-Z0-9' ]", "", (resp.text or "").upper())
        want = re.sub(r"[^A-Z0-9' ]", "", expected.upper())
        return want in got
    except Exception as exc:
        print(f"      gemini vision check failed ({str(exc)[:60]})")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def strongest_mid_beat(beats: list[dict]) -> dict | None:
    """A strong mid-video emotional beat: most emphasis words, longer wins."""
    mids = [b for b in beats[1:-1]
            if (float(b.get("end", 0) or 0) - float(b.get("start", 0) or 0)) >= 1.5]
    if not mids:
        mids = beats[1:-1] or beats
    if not mids:
        return None
    return max(mids, key=lambda b: (len(b.get("emphasis_words") or []),
                                    float(b.get("end", 0)) -
                                    float(b.get("start", 0))))


def find_run(output_dir: str, run_id: str | None) -> Path:
    base = Path(output_dir)
    if run_id:
        folder = base / run_id
        if not folder.is_dir():
            sys.exit(f"ERROR: run folder not found: {folder}")
        return folder
    candidates = [d for d in base.iterdir()
                  if d.is_dir() and (d / "final_short.mp4").is_file()]
    if not candidates:
        sys.exit("ERROR: no run folder with final_short.mp4 (render first)")
    return max(candidates, key=lambda d: d.stat().st_mtime)


def _variant_contexts(run_folder: Path, variant_pref: str,
                      api_key: str | None) -> dict:
    """Texts + per-variant illustration contexts from the beats JSON."""
    timings_file = run_folder / "word_timings.json"
    if not timings_file.is_file():
        raise RuntimeError("word_timings.json missing (old run?)")
    timings = json.loads(timings_file.read_text(encoding="utf-8"))
    beats = [b for b in (timings.get("beats") or [])
             if isinstance(b, dict) and b.get("text")]
    mode = "beats" if beats else "classic"

    if beats:
        hook_beat = beats[0]
        hook_text = str(hook_beat["text"]).strip()
        emphasis = list(hook_beat.get("emphasis_words") or [])
        mid_beat = strongest_mid_beat(beats)
        mid_text = str(mid_beat["text"]).strip() if mid_beat else ""
        mid_emphasis = list(mid_beat.get("emphasis_words") or []) \
            if mid_beat else []
    else:
        script = timings.get("script", "")
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", script)
                     if s.strip()]
        hook_beat = {"emotion": "", "visual_concept": script[:120]}
        hook_text = sentences[0] if sentences else script[:80]
        emphasis = []
        mid_beat = None
        mid_text = sentences[len(sentences) // 2] if len(sentences) > 2 else ""
        mid_emphasis = []

    texts = resolve_thumbnail_texts(hook_text, mid_text, emphasis, api_key)

    def ctx_for(beat: dict | None, caption: str) -> dict:
        return {
            "run_id": run_folder.name,
            "caption": caption,
            "emotion": str((beat or {}).get("emotion", "") or ""),
            "visual_concept": str((beat or {}).get("visual_concept", "") or ""),
        }

    contexts = {
        "hook": ctx_for(hook_beat, texts["hook"]),
        "midpoint": ctx_for(mid_beat, texts["mid"]),
        "clean": ctx_for(mid_beat or hook_beat, ""),   # clean = no text
    }
    return {"mode": mode, "texts": texts, "contexts": contexts,
            "hook_emphasis": emphasis}


def generate_variant(run_folder: Path, name: str, ctx: dict, caption: str,
                     provider: str, api_key: str | None,
                     net_deadline: float) -> dict | None:
    """One variant -> {youtube: 1080x1920 JPG (Shorts primary),
    instagram: 1080x1920 PNG cover, youtube_wide: 1280x720 JPG (legacy)}.
    The vertical render is generated ONCE and split into the two upload
    files - one AI image, two encodes."""
    th_dir = run_folder / "thumbnails"
    work_dir = th_dir / "_work"
    info: dict = {"text_used": caption, "original_text": caption,
                  "emotion": ctx.get("emotion", ""),
                  "visual_concept": ctx.get("visual_concept", ""),
                  "frame_timestamp": None, "files": {}, "cost": "$0"}
    models_seen, any_file = [], False

    def _emit_vertical(base_png: Path) -> None:
        """Split one finished vertical render into the two upload files."""
        yt_dest = th_dir / f"{name}_youtube.jpg"       # Shorts thumbnails.set
        ig_dest = th_dir / f"{name}_instagram.png"     # Reels cover
        _png_to_jpg_bounded(base_png, yt_dest)
        ig_dest.write_bytes(base_png.read_bytes())
        info["files"]["youtube"] = str(yt_dest.relative_to(run_folder))
        info["files"]["instagram"] = str(ig_dest.relative_to(run_folder))

    for wide in (True, False):
        if wide:
            dest = th_dir / f"{name}_youtube_wide.jpg"      # legacy 16:9
        else:
            dest = work_dir / f"{name}_vertical_base.png"   # work render
        seed = seed_for(run_folder.name, name, "wide" if wide else "vertical")
        base_done = False

        if provider in ("auto", "pollinations"):
            if time.time() < net_deadline:
                prompt = build_prompt(name, caption, ctx, wide,
                                      paint_text=False)
                data, _ctype, model = pollinations_image(prompt, wide, seed)
                if data:
                    save_image(data, dest, wide)
                    if caption:
                        layout = overlay_headline(dest, caption, wide)
                        info["layout"] = (f"{len(layout['lines'])} lines @ "
                                          f"{layout['font_px']}px")
                    info["model"] = model
                    models_seen.append(f"pollinations-{model}")
                    any_file = base_done = True
            else:
                print(f"      {name}: network art budget spent -> "
                      "local poster")
        elif provider == "gemini" and api_key:
            prompt = build_prompt(name, caption, ctx, wide,
                                  paint_text=bool(caption))
            data = gemini_image(prompt, api_key)
            if data and caption:
                if not gemini_text_check(data, caption, api_key):
                    print("      gemini: baked text wrong -> re-generating "
                          "text-free + local typography")
                    data = gemini_image(
                        build_prompt(name, caption, ctx, wide,
                                     paint_text=False), api_key) or b""
            if data:
                dest.parent.mkdir(parents=True, exist_ok=True)
                base = work_dir / f"{name}_base_{'wide' if wide else 'vert'}.png"
                base.write_bytes(data)
                save_image(base.read_bytes(), dest, wide)
                if caption:
                    overlay_headline(dest, caption, wide)
                info["model"] = "gemini"
                models_seen.append("gemini")
                any_file = base_done = True

        if not base_done and provider in ("auto", "local"):
            art = local_artwork(ctx, wide, seed)
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.suffix.lower() == ".jpg":
                art.convert("RGB").save(dest, "JPEG", quality=92,
                                        optimize=True)
            else:
                art.save(dest, "PNG")
            if caption:
                layout = overlay_headline(dest, caption, wide)
                info["layout"] = (f"{len(layout['lines'])} lines @ "
                                  f"{layout['font_px']}px")
            info["model"] = "local_artwork"
            models_seen.append("local_artwork")
            any_file = True

        # map the finished render onto the manifest's upload keys
        if base_done or (provider in ("auto", "local") and dest.is_file()):
            if wide:
                info["files"]["youtube_wide"] = \
                    str(dest.relative_to(run_folder))
            else:
                _emit_vertical(dest)

    if any_file:
        info["image_provider"] = " -> ".join(dict.fromkeys(models_seen)) \
            or "unknown"
        print(f"      variant '{name}': {info['image_provider']}"
              f"{' | ' + info.get('layout', '') if caption else ''}")
        return info
    print(f"      variant '{name}': no image could be generated - skipped")
    return None


def build_variants(run_folder: Path, variant_pref: str,
                   api_key: str | None, strict: bool) -> dict:
    global PROVIDER
    provider = PROVIDER
    if provider == "gemini" and not api_key:
        print("      THUMB_IMAGE_PROVIDER=gemini but GEMINI_API_KEY missing "
              "-> falling back to auto (free) chain")
        provider = "auto"

    parsed = _variant_contexts(run_folder, variant_pref, api_key)
    texts, contexts = parsed["texts"], parsed["contexts"]
    net_deadline = time.time() + POLLINATIONS_GLOBAL_BUDGET

    variants: dict[str, dict] = {}
    for name in ("hook", "midpoint", "clean"):
        if name == "midpoint" and not contexts["midpoint"]["caption"]:
            continue                          # no mid text -> skip midpoint
        caption = contexts[name]["caption"]
        try:
            info = generate_variant(run_folder, name, contexts[name],
                                    caption, provider, api_key, net_deadline)
        except Exception as exc:
            print(f"      variant '{name}': failed ({str(exc)[:90]})")
            info = None
        if info:
            variants[name] = info

    return {"variants": variants, "texts": texts, "mode": parsed["mode"],
            "preferred": variant_pref}


def _list_models() -> int:
    """Provider/price report - works WITHOUT any API key."""
    print("=" * 60)
    print("  THUMBNAIL image providers")
    print("=" * 60)
    print(f"  THUMB_IMAGE_PROVIDER = {PROVIDER}")
    print(f"  pollinations models  = {', '.join(POLLINATIONS_MODELS)}"
          + (f" (forced: {POLLINATIONS_MODEL_ENV})" if POLLINATIONS_MODEL_ENV
             else ""))
    try:
        import requests as rq
        resp = rq.get("https://image.pollinations.ai/models", timeout=20)
        names = [m.get("name", str(m)) if isinstance(m, dict) else str(m)
                 for m in resp.json()]
        print(f"  pollinations live    : {', '.join(names[:12])}")
    except Exception as exc:
        print(f"  pollinations probe   : unavailable ({str(exc)[:60]})")
    print("  cost per image       : $0 (public endpoint, no key)")
    key = (os.getenv("GEMINI_API_KEY", "") or "").strip()
    if key:
        print(f"  gemini (legacy paid) : {', '.join(_GEMINI_IMAGE_MODELS)} "
              "+ text shorten via " + GEMINI_MODELS[0])
    else:
        print("  gemini (legacy paid) : key not set - auto/local chains only")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate free thumbnail variants for the newest (or "
                    "given) run")
    parser.add_argument("--run-id", help="run folder under --output-dir")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--video", help="explicit final_short.mp4 (run = parent)")
    parser.add_argument("--variant", choices=("hook", "midpoint", "clean"),
                        default=None,
                        help="which variant becomes the upload default "
                             "(default: THUMBNAIL_VARIANT env, else hook)")
    parser.add_argument("--auto-upload", choices=("true", "false"),
                        default=None,
                        help="false = review only, upload step will not "
                             "attach (default: AUTO_UPLOAD_THUMBNAIL env)")
    parser.add_argument("--strict", action="store_true",
                        help="exit non-zero on failure (CI default is soft)")
    parser.add_argument("--list-models", action="store_true",
                        help="print provider/model info and exit (no key)")
    args = parser.parse_args()

    load_environment(None)
    if args.list_models:
        return _list_models()
    api_key = (os.getenv("GEMINI_API_KEY", "") or "").strip() or None

    run_folder = Path(args.video).parent if args.video \
        else find_run(args.output_dir, args.run_id)
    variant_pref = (args.variant or os.getenv("THUMBNAIL_VARIANT", "")
                    or DEFAULT_VARIANT).strip().lower()
    if variant_pref not in ("hook", "midpoint", "clean"):
        variant_pref = DEFAULT_VARIANT
    auto_upload = (args.auto_upload or
                   os.getenv("AUTO_UPLOAD_THUMBNAIL", "") or "true").lower() \
        not in ("0", "false", "off", "no")

    print("=" * 60)
    print("  STEP 2.6 - THUMBNAILS (free: pollinations + Anton typography)")
    print(f"  run: {run_folder.name} | provider: {PROVIDER} "
          f"| default variant: {variant_pref} | auto-attach: {auto_upload}")
    print("=" * 60)

    t0 = time.time()
    try:
        result = build_variants(run_folder, variant_pref, api_key, args.strict)
    except Exception as exc:
        print(f"WARNING: thumbnail generation failed - pipeline continues "
              f"without thumbnails ({str(exc)[:120]})")
        if args.strict:
            return 1
        return 0

    variants = result["variants"]
    if not variants:
        print("WARNING: no thumbnail variant could be generated - pipeline "
              "continues without thumbnails")
        return 1 if args.strict else 0

    # selection: preferred variant first, then hook > midpoint > clean
    order = [variant_pref] + [v for v in ("hook", "midpoint", "clean")
                              if v != variant_pref]
    chosen = next((v for v in order if variants.get(v)), None)
    selected = None
    if chosen:
        selected = {
            "variant": chosen,
            "youtube": str((run_folder / "thumbnails" / f"{chosen}_youtube.jpg")
                           .relative_to(run_folder)),
            "instagram": str((run_folder / "thumbnails" /
                              f"{chosen}_instagram.png")
                             .relative_to(run_folder)),
            "attach": auto_upload,
        }
        # tiny mobile-feed legibility proof (what it looks like scrolled past)
        try:
            from PIL import Image
            img = Image.open(run_folder / selected["instagram"])
            img.resize((270, 480), Image.LANCZOS).save(
                run_folder / "thumbnails" / "preview_mobile_selected.png")
            img_yt = Image.open(run_folder / "thumbnails" /
                                f"{chosen}_youtube.jpg")
            # the Shorts upload spec is vertical now - preview it as 9:16
            img_yt.resize((180, 320), Image.LANCZOS).save(
                run_folder / "thumbnails" / "preview_mobile_youtube.png")
        except Exception:
            pass

    manifest = {
        "run_id": run_folder.name,
        "video": "final_short.mp4",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "mode": result["mode"],
        "generator": "pollinations + Anton typography (free, no video "
                     "frames, Shorts-first 9:16)",
        "image_provider": PROVIDER,
        "cost": "$0",
        "config": {"thumbnail_variant": variant_pref,
                   "auto_upload_thumbnail": auto_upload,
                   "image_provider": PROVIDER,
                   "pollinations_budget_s": POLLINATIONS_GLOBAL_BUDGET},
        "variants": variants,
        "selected": selected,
    }
    manifest_path = run_folder / "thumbnails" / "thumbnail_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2),
                             encoding="utf-8")

    # review folder hygiene: drop the working candidate files
    try:
        for p in (run_folder / "thumbnails" / "_work").glob("*"):
            p.unlink()
    except Exception:
        pass

    print()
    print(f"  thumbnails ready in {time.time() - t0:.1f}s -> "
          f"{manifest_path.parent}")
    for name, info in variants.items():
        mark = " <-- default for upload" if chosen and name == chosen else ""
        print(f"    {name:9s} {info.get('image_provider', '?'):>26s} "
              f"text=\"{info.get('text_used', '')[:34]}\"{mark}")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
